# Generated by Django 5.2.6 on 2025-09-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_student_registration_paid_student_user_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='predictor.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='predictor.donor'),
        ),
    ]
