# Generated by Django 5.2.6 on 2025-09-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_student_wallet_balance_transaction_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('bursary', 'Bursary'), ('tuition', 'Tuition')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.donor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_payments', to='predictor.student')),
            ],
        ),
    ]
