# Generated by Django 5.2.6 on 2025-09-12 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_universitypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='top_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitypayment',
            name='payment_type',
            field=models.CharField(choices=[('bursary', 'Bursary'), ('tuition', 'Tuition'), ('living', 'Living Costs')], default='bursary', max_length=50),
        ),
        migrations.AlterField(
            model_name='universitypayment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('student', 'donor')},
        ),
    ]
