# Generated by Django 5.2.6 on 2025-09-13 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_match_top_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='csr_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='total_donated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
