# Generated by Django 5.2.6 on 2025-09-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_donor_csr_score_donor_total_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bursary_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.bursaryrequest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.match'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='predictor.student'),
        ),
    ]
